// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyectile.Server.Entitys;

#nullable disable

namespace Proyectile.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240329153610_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyectile.Server.Entitys.Models.Objetivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nchar(300)");

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Objetivos", (string)null);
                });

            modelBuilder.Entity("Proyectile.Server.Entitys.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nchar(200)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Proyectos", (string)null);
                });

            modelBuilder.Entity("Proyectile.Server.Entitys.Models.Tarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nchar(300)");

                    b.Property<int>("ObjetivoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("Proyectile.Server.Entitys.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nchar(100)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nchar(120)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nchar(270)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("Proyectile.Server.Entitys.Models.UsuarioProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProyectoID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsuariosProyectos", (string)null);
                });

            modelBuilder.Entity("Proyectile.Server.Entitys.Models.UsuarioTarea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("TareaID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UsuariosTareas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
